import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./_components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#15121b",
        foreground: "hsl(var(--foreground))",
        "on-surface-variant": "#ccc3d8",
        "inverse-primary": "#732ee4",
        "tertiary-fixed-dim": "#ffb784",
        "on-error": "#690005",
        "surface-container-lowest": "#100d16",
        "surface": "#15121b",
        "surface-container-highest": "#37333e",
        "on-primary-fixed": "#25005a",
        "surface-container": "#221e28",
        "secondary-fixed-dim": "#4cd7f6",
        "primary-fixed-dim": "#d2bbff",
        "error-container": "#93000a",
        "secondary": "#4cd7f6",
        "on-background": "#e8dfee",
        "on-tertiary-fixed-variant": "#713700",
        "tertiary": "#ffb784",
        "on-primary": "#3f008e",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed-variant": "#004e5c",
        "on-tertiary": "#4f2500",
        "primary": "#d2bbff",
        "secondary-fixed": "#acedff",
        "surface-bright": "#3c3742",
        "on-secondary": "#003640",
        "on-tertiary-container": "#ffe0cd",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-dim": "#15121b",
        "surface-variant": "#37333e",
        "on-secondary-fixed": "#001f26",
        "tertiary-container": "#a15100",
        "outline-variant": "#4a4455",
        "surface-container-low": "#1d1a24",
        "error": "#ffb4ab",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#eaddff",
        "on-primary-container": "#ede0ff",
        "secondary-container": "#03b5d3",
        "surface-tint": "#d2bbff",
        "on-secondary-container": "#00424e",
        "primary-container": "#7c3aed",
        "tertiary-fixed": "#ffdcc6",
        "inverse-on-surface": "#332f39",
        "surface-container-high": "#2c2833",
        "outline": "#958da1",
        "on-surface": "#e8dfee",
        "inverse-surface": "#e8dfee",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "lg": "24px",
        "sm": "8px",
        "unit": "4px",
        "margin": "32px",
        "container-max": "1440px",
        "gutter": "24px",
        "md": "16px",
        "xs": "4px",
        "xl": "48px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "h1": ["Syne"],
        "h2": ["Syne"],
        "h3": ["Syne"],
        "button": ["Inter"],
        "display-hero": ["Syne"],
        "label-mono": ["JetBrains Mono"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "h1": ["48px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "h2": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "h3": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "button": ["14px", { "lineHeight": "1.0", "fontWeight": "600" }],
        "display-hero": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    },
  },
} satisfies Config;
