import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./_components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ffb4ab",
        "on-background": "#e1e2ee",
        "primary-container": "#006aff",
        "on-secondary-container": "#a6b9de",
        "surface-container-high": "#272a33",
        "on-tertiary-fixed-variant": "#802900",
        "surface-dim": "#10131c",
        "background": "#10131c",
        "tertiary-container": "#cd4700",
        "on-surface-variant": "#c2c6d8",
        "secondary-fixed-dim": "#b4c7ec",
        "surface-container": "#1d1f28",
        "primary-fixed-dim": "#b2c5ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#380d00",
        "surface-tint": "#b2c5ff",
        "tertiary-fixed-dim": "#ffb59a",
        "platform-youtube": "#FF0000",
        "status-ready": "#34C759",
        "surface-container-lowest": "#0b0e16",
        "secondary-fixed": "#d6e3ff",
        "on-secondary-fixed-variant": "#354766",
        "on-error": "#690005",
        "on-primary-container": "#fefbff",
        "outline-variant": "#424655",
        "on-primary-fixed": "#001847",
        "on-primary-fixed-variant": "#0040a1",
        "on-surface": "#e1e2ee",
        "surface-bright": "#363942",
        "on-primary": "#002c72",
        "surface": "#10131c",
        "on-secondary-fixed": "#061b38",
        "tertiary-fixed": "#ffdbcf",
        "platform-twitch": "#9146FF",
        "neutral-muted": "#8D8D8D",
        "outline": "#8c90a1",
        "on-tertiary": "#5b1b00",
        "on-secondary": "#1e314f",
        "primary-fixed": "#dae2ff",
        "secondary-container": "#374969",
        "tertiary": "#ffb59a",
        "secondary": "#b4c7ec",
        "inverse-surface": "#e1e2ee",
        "inverse-primary": "#0056d1",
        "surface-variant": "#32343e",
        "primary": "#b2c5ff",
        "error-container": "#93000a",
        "status-live": "#FF3B30",
        "inverse-on-surface": "#2d3039",
        "on-tertiary-container": "#fffbff",
        "surface-container-low": "#191b24",
        "surface-container-highest": "#32343e",
        "inverse-on-surface": "#2d3039",
        "on-tertiary-container": "#fffbff",
        "surface-container-low": "#191b24",
        "surface-container-highest": "#32343e",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "base": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "gutter": "24px"
      },
      keyframes: {
        "pulse-red": {
          "0%": { "box-shadow": "0 0 0 0 rgba(255, 59, 48, 0.7)" },
          "70%": { "box-shadow": "0 0 0 10px rgba(255, 59, 48, 0)" },
          "100%": { "box-shadow": "0 0 0 0 rgba(255, 59, 48, 0)" }
        },
        "dash": {
          "to": { "stroke-dashoffset": "0" }
        }
      },
      animation: {
        "pulse-live": "pulse-red 2s infinite",
        "dash": "dash 3s linear forwards"
      },
      fontFamily: {
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "headline-xl": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "body-base": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "14px", "fontWeight": "500" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-caps": ["10px", { "lineHeight": "14px", "letterSpacing": "0.12em", "fontWeight": "600" }],
        "data-mono": ["12px", { "lineHeight": "16px", "fontWeight": "500" }]
      }
    },
  },
} satisfies Config;
