import type { Config } from "tailwindcss";

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./_components/**/*.{js,ts,jsx,tsx,mdx}",
    "../../packages/**/*.{ts,tsx,js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#ff5f1f",
        "inverse-surface": "#e5e2e3",
        "on-primary": "#5c1900",
        "on-secondary-fixed-variant": "#44474b",
        "primary-fixed-dim": "#ffb59c",
        "on-secondary-container": "#b6b8be",
        "surface-container": "#1f1f20",
        "outline": "#aa897f",
        "primary-fixed": "#ffdbcf",
        "secondary": "#c4c6cc",
        "on-primary-fixed": "#390c00",
        "tertiary": "#c9c6c5",
        "on-tertiary-fixed-variant": "#474646",
        "on-primary-fixed-variant": "#832700",
        "tertiary-fixed": "#e5e2e1",
        "inverse-on-surface": "#303031",
        "outline-variant": "#5b4138",
        "secondary-fixed": "#e0e2e8",
        "on-tertiary-fixed": "#1c1b1b",
        "on-surface-variant": "#e3bfb3",
        "on-primary-container": "#561700",
        "on-tertiary": "#313030",
        "on-tertiary-container": "#2d2c2c",
        "surface-dim": "#131314",
        "primary": "#ffb59c",
        "on-surface": "#e5e2e3",
        "inverse-primary": "#ab3600",
        "surface-container-lowest": "#0e0e0f",
        "error-container": "#93000a",
        "surface-container-high": "#2a2a2b",
        "on-secondary": "#2d3135",
        "on-error": "#690005",
        "secondary-container": "#46494e",
        "surface-container-low": "#1b1b1c",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c4c6cc",
        "tertiary-fixed-dim": "#c9c6c5",
        "surface-bright": "#39393a",
        "background": "#131314",
        "surface-variant": "#353436",
        "surface-container-highest": "#353436",
        "surface": "#131314",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#959393",
        "on-secondary-fixed": "#181c20",
        "on-background": "#e5e2e3",
        "surface-tint": "#ffb59c",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "container-max": "1440px",
        "margin": "32px",
        "unit": "4px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "label-caps": ["Space Grotesk", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "data-mono": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-base": ["16px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "data-mono": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600" }]
      }
    },
  },
} satisfies Config;
