/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  createdAt: Generated<Timestamp>;
  email: string;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  password: string;
  updatedAt: Generated<Timestamp>;
}

export interface Comments {
  accountId: string;
  archivedAt: Timestamp | null;
  content: string;
  createdAt: Generated<Timestamp>;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface EmailLists {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isDefault: boolean | null;
  profileId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface EmailListSubscribers {
  createdAt: Generated<Timestamp>;
  email: string;
  emailListId: string;
  firstName: string | null;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface EmailRecipients {
  createdAt: Generated<Timestamp>;
  emailId: string;
  failedAt: Timestamp | null;
  firstName: string | null;
  id: Generated<string>;
  recipientEmail: string;
  sentAt: Timestamp | null;
  status: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Emails {
  createdAt: Generated<Timestamp>;
  emailListId: string | null;
  emailTemplateId: string;
  id: Generated<string>;
  profileId: string;
  recipientEmail: string | null;
  sendDate: Timestamp | null;
  status: string | null;
  subject: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface EmailTemplates {
  config: Json;
  content: Json;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  profileId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface EmailVariables {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  profileId: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface EventPasses {
  checkedInAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  eventId: string;
  eventTicketId: string;
  eventTicketOrderItemId: string;
  id: Generated<string>;
  ownerEmail: string;
  ownerName: string;
  sessionId: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Events {
  actionLink: string | null;
  actionText: string | null;
  address: Json;
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  dateTime: Timestamp;
  description: string | null;
  id: Generated<string>;
  profileId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface EventTicketOrderItems {
  createdAt: Generated<Timestamp>;
  eventTicketId: string;
  eventTicketOrderId: string;
  id: Generated<string>;
  price: Numeric;
  quantity: number;
  updatedAt: Generated<Timestamp>;
}

export interface EventTicketOrders {
  createdAt: Generated<Timestamp>;
  email: string;
  eventId: string;
  firstName: string;
  id: Generated<string>;
  lastName: string;
  paymentId: string | null;
  paymentProviderName: string | null;
  status: string;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface EventTickets {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string;
  eventId: string;
  id: Generated<string>;
  order: number;
  price: Numeric;
  quantity: number;
  sold: Generated<number>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Likes {
  accountId: string;
  createdAt: Generated<Timestamp>;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Media {
  createdAt: Generated<Timestamp>;
  filename: string | null;
  id: Generated<string>;
  name: string | null;
  parent: string;
  productStoreId: string | null;
  profileId: string;
  size: Int8;
  type: string;
  updatedAt: Generated<Timestamp>;
  url: string;
}

export interface MediaMappings {
  createdAt: Generated<Timestamp>;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  mediaId: string;
  order: number;
  updatedAt: Generated<Timestamp>;
}

export interface MembershipBenefits {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  profileId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Memberships {
  accountId: string;
  changedToMembershipId: string | null;
  createdAt: Generated<Timestamp>;
  endDate: Timestamp | null;
  id: Generated<string>;
  membershipTierId: string;
  profileId: string;
  profilePaymentSubscriptionId: string | null;
  startDate: Timestamp;
  status: string;
  updatedAt: Generated<Timestamp>;
}

export interface MembershipTiers {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  isDefault: Generated<boolean | null>;
  name: string;
  order: Generated<number>;
  payWhatYouWant: Generated<boolean | null>;
  payWhatYouWantMaximum: number | null;
  payWhatYouWantMinimum: number | null;
  priceMonthly: number | null;
  priceYearly: number | null;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface MembershipTiersBenefits {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  membershipBenefitId: string;
  membershipTierId: string;
  order: number;
  updatedAt: Generated<Timestamp>;
}

export interface OrderDeliveryGroups {
  createdAt: Generated<Timestamp>;
  deliveryType: string;
  externalId: string | null;
  fileName: string | null;
  fileSize: number | null;
  fileUrl: string | null;
  id: Generated<string>;
  isGift: Generated<boolean>;
  orderId: string;
  productStoreId: string | null;
  recipientEmail: string;
  recipientName: string;
  shippingCost: Numeric | null;
  status: Generated<string>;
  subTotal: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface OrderItems {
  color: string | null;
  coverImage: string | null;
  createdAt: Generated<Timestamp>;
  externalId: string | null;
  id: Generated<string>;
  isGift: Generated<boolean>;
  orderDeliveryGroupId: string | null;
  orderId: string;
  payWhatYouWant: Generated<boolean>;
  price: Numeric;
  productId: string;
  productVariantId: string;
  quantity: number;
  recipientEmail: string | null;
  recipientMessage: string | null;
  recipientName: string | null;
  size: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Orders {
  accountId: string | null;
  createdAt: Generated<Timestamp>;
  email: string | null;
  firstName: string | null;
  id: Generated<string>;
  lastName: string | null;
  paymentId: string | null;
  paymentProviderName: string;
  profileId: string;
  status: string;
  totalAmount: Numeric;
  updatedAt: Generated<Timestamp>;
}

export interface PostCollectionPosts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  order: number;
  postCollectionId: string;
  "postId ": string;
  updatedAt: Generated<Timestamp>;
}

export interface PostCollections {
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  postType: string;
  profileId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Posts {
  archivedAt: Timestamp | null;
  caption: string;
  createdAt: Generated<Timestamp>;
  createdBy: string;
  id: Generated<string>;
  membershipTiers: Generated<Json>;
  profileId: string;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductCategories {
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Products {
  archivedAt: Timestamp | null;
  artist: string | null;
  categoryId: string;
  createdAt: Generated<Timestamp>;
  credits: string | null;
  description: string;
  externalId: string | null;
  id: Generated<string>;
  isFeatured: Generated<boolean>;
  isSingle: Generated<boolean | null>;
  productStoreId: string | null;
  profileId: string;
  publishedAt: Timestamp | null;
  tags: string[] | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductStores {
  accessToken: string;
  createdAt: Generated<Timestamp>;
  defaults: Generated<Json>;
  externalId: string;
  id: Generated<string>;
  lastSyncedAt: Timestamp | null;
  name: string;
  profileId: string;
  provider: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProductVariants {
  availabilityStatus: Generated<string>;
  color: string | null;
  createdAt: Generated<Timestamp>;
  deliveryType: string;
  description: string | null;
  externalId: string | null;
  id: Generated<string>;
  isDefault: Generated<boolean>;
  payWhatYouWant: Generated<boolean | null>;
  payWhatYouWantMaximum: number | null;
  price: Numeric;
  productId: string;
  size: string | null;
  title: string;
  upcCode: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface ProductVariantTracks {
  artist: string | null;
  createdAt: Generated<Timestamp>;
  credits: string | null;
  description: string | null;
  hasExplicitContent: Generated<boolean>;
  id: Generated<string>;
  isFeatured: Generated<boolean>;
  isrcCode: string | null;
  productVariantId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfileAuthorizations {
  accountId: string;
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isOwner: Generated<boolean>;
  permissions: Generated<Json>;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfileConfigurations {
  address: Json | null;
  id: Generated<string>;
  paymentProviderName: string | null;
  paymentProviderPrivateKey: string | null;
  paymentProviderPublicKey: string | null;
  paymentProviderWebhookSecret: string | null;
  profileId: string;
  pwaConfig: Json | null;
  r2AccessKeyId: string | null;
  r2BucketName: string | null;
  r2BucketUrl: string | null;
  r2Endpoint: string | null;
  r2Region: string | null;
  r2SecretAccessKey: string | null;
  smtpFrom: string | null;
  smtpHost: string | null;
  smtpPassword: string | null;
  smtpPort: string | null;
  smtpUsername: string | null;
  storageType: string | null;
}

export interface ProfileOnboardingSteps {
  actionPath: string;
  actionText: string;
  completedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  description: string;
  helpLink: string | null;
  id: string;
  profileId: string;
  step: number;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfilePaymentCustomers {
  accountId: string;
  createdAt: Generated<Timestamp>;
  customerId: string;
  id: Generated<string>;
  paymentProviderName: string;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfilePaymentPrices {
  amount: number;
  billingCycle: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  paymentProviderName: string;
  priceId: string;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfilePaymentProducts {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  paymentProviderName: string;
  productId: string;
  productType: string;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ProfilePaymentSubscriptions {
  accountId: string;
  createdAt: Generated<Timestamp>;
  currentPeriodEnd: Timestamp;
  currentPeriodStart: Timestamp;
  customerId: string;
  id: Generated<string>;
  paymentProfilePriceId: string;
  paymentProviderName: string;
  paymentProviderSubscriptionId: string;
  profileId: string;
  status: string;
  updatedAt: Generated<Timestamp>;
}

export interface Profiles {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  subdomain: string;
  updatedAt: Generated<Timestamp>;
}

export interface Saves {
  accountId: string;
  archivedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  entityId: string;
  entityType: string;
  id: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isValid: Generated<boolean>;
  updatedAt: Generated<Timestamp>;
  userAgent: Json | null;
}

export interface SmartLinkEvents {
  createdAt: Generated<Timestamp>;
  eventData: Json;
  eventType: string;
  id: Generated<string>;
  smartLinkId: string;
  updatedAt: Generated<Timestamp>;
}

export interface SmartLinks {
  archivedAt: Timestamp | null;
  content: Json;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  path: string;
  profileId: string;
  template: string | null;
  themeSettings: Json;
  thumbnail: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface StreamBroadcastChannels {
  createdAt: Generated<Timestamp>;
  externalBroadcastId: string | null;
  externalChatId: string | null;
  externalStreamId: string | null;
  id: Generated<string>;
  nextPageToken: string | null;
  streamBroadcastId: string;
  streamChannelId: string;
  updatedAt: Generated<Timestamp>;
  views: Generated<number>;
}

export interface StreamBroadcastComments {
  content: string;
  createdAt: Generated<Timestamp>;
  externalId: string | null;
  id: Generated<string>;
  isAdmin: Generated<boolean>;
  name: string;
  publishedAt: Timestamp | null;
  streamBroadcastChannelId: string;
  updatedAt: Generated<Timestamp>;
}

export interface ScheduledStreams {
  id: Generated<string>;
  profileId: string;
  title: string;
  videoUrl: string;
  videoFilename: string;
  scheduledAt: Timestamp;
  status: string;
  createdAt: Generated<Timestamp>;
  updatedAt: Generated<Timestamp>;
}

export interface StreamBroadcasts {
  createdAt: Generated<Timestamp>;
  egressId: string | null;
  endedAt: Timestamp | null;
  eventId: string | null;
  generatedThumbnailUrl: string | null;
  id: Generated<string>;
  liveUrl: string | null;
  profileId: string;
  startDate: Timestamp | null;
  startedAt: Timestamp;
  streamTemplateId: string;
  thumbnailUrl: string | null;
  title: string;
  updatedAt: Generated<Timestamp>;
  vodUrl: string | null;
}

export interface StreamChannels {
  brandingSettings: Json | null;
  channelProvider: string;
  createdAt: Generated<Timestamp>;
  credentials: Json;
  currentBroadcastId: string | null;
  currentEndpoint: string | null;
  currentStreamId: string | null;
  externalId: string | null;
  id: Generated<string>;
  profileId: string;
  title: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface StreamTemplateChannels {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  streamChannelId: string;
  streamTemplateId: string;
  updatedAt: Generated<Timestamp>;
}

export interface StreamTemplates {
  config: Json | null;
  createdAt: Generated<Timestamp>;
  description: string | null;
  eventId: string | null;
  id: Generated<string>;
  isLive: boolean | null;
  profileId: string;
  scenes: Json;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface WebsiteEvents {
  createdAt: Generated<Timestamp>;
  eventData: Json;
  eventType: string;
  id: Generated<string>;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface WebsiteMessages {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  message: string;
  name: string;
  profileId: string;
  updatedAt: Generated<Timestamp>;
}

export interface WebsiteVersionPages {
  content: Generated<Json>;
  createdAt: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  pathname: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  websiteVersionId: string;
}

export interface WebsiteVersions {
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  isActive: Generated<boolean>;
  profileId: string;
  themeName: string;
  themeSettings: Json;
  themeThumbnail: string;
  themeVersion: string;
  updatedAt: Generated<Timestamp>;
  version: Generated<number>;
}

export interface DB {
  accounts: Accounts;
  comments: Comments;
  emailLists: EmailLists;
  emailListSubscribers: EmailListSubscribers;
  emailRecipients: EmailRecipients;
  emails: Emails;
  emailTemplates: EmailTemplates;
  emailVariables: EmailVariables;
  eventPasses: EventPasses;
  events: Events;
  eventTicketOrderItems: EventTicketOrderItems;
  eventTicketOrders: EventTicketOrders;
  eventTickets: EventTickets;
  likes: Likes;
  media: Media;
  mediaMappings: MediaMappings;
  membershipBenefits: MembershipBenefits;
  memberships: Memberships;
  membershipTiers: MembershipTiers;
  membershipTiersBenefits: MembershipTiersBenefits;
  orderDeliveryGroups: OrderDeliveryGroups;
  orderItems: OrderItems;
  orders: Orders;
  postCollectionPosts: PostCollectionPosts;
  postCollections: PostCollections;
  posts: Posts;
  productCategories: ProductCategories;
  products: Products;
  productStores: ProductStores;
  productVariants: ProductVariants;
  productVariantTracks: ProductVariantTracks;
  profileAuthorizations: ProfileAuthorizations;
  profileConfigurations: ProfileConfigurations;
  profileOnboardingSteps: ProfileOnboardingSteps;
  profilePaymentCustomers: ProfilePaymentCustomers;
  profilePaymentPrices: ProfilePaymentPrices;
  profilePaymentProducts: ProfilePaymentProducts;
  profilePaymentSubscriptions: ProfilePaymentSubscriptions;
  profiles: Profiles;
  saves: Saves;
  sessions: Sessions;
  smartLinkEvents: SmartLinkEvents;
  smartLinks: SmartLinks;
  scheduledStreams: ScheduledStreams;
  streamBroadcastChannels: StreamBroadcastChannels;
  streamBroadcastComments: StreamBroadcastComments;
  streamBroadcasts: StreamBroadcasts;
  streamChannels: StreamChannels;
  streamTemplateChannels: StreamTemplateChannels;
  streamTemplates: StreamTemplates;
  websiteEvents: WebsiteEvents;
  websiteMessages: WebsiteMessages;
  websiteVersionPages: WebsiteVersionPages;
  websiteVersions: WebsiteVersions;
}
